### ISSUE TITLE
Dropdown in menu

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/qtbase-os2#122]
When you hit a dropdown menu at the top bar, you can move the mouse to the right and the next menu opens. But you can't do the same in the left direction. The menu never opens. I mean it opens if you klick on it but not automatically when you move the mouse only.

**Comment by dmik** [comment]
I can confirm this, it's like that since long. Needs a fix (and a deeper code investigation).

**Comment by SilvanScherrer** [comment]
Iirc this was the case since every qt5 release

**Comment by dmik** [comment]
@lerdmann just to be sure, do you also see it in a much simpler example called menus.exe (Programs -> bitwiseworks Apps and Ports ->Qt 5 Examples 5.15.2 -> examples -> widgets -> mainwindows -> menus)? I see it there too.

**Comment by dmik** [comment]
Turned out that this bug was triggered by a really hairy bug in OS/2 headers which define macros SHORT1FROMMP and SHORT2FROMMP which, despite the names, actually return USHORT. As a result, when this USHORT is converted to LONG during assignment to POINTL members, SHORT -1 (USHORT 65535) becomes LONG 65535, -2 becomes 65534 and so on.

As a result, Qt would see weird X coordinates far beyond the screen when OS/2 reported negative X for a window when the mouse was moved behind its left edge.

The fix just explicitly casts USHORT to SHORT before assigning to LONG to avoid this.
